//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnakeGraphicEngine.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class GraphicColorSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static GraphicColorSettings defaultInstance = ((GraphicColorSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new GraphicColorSettings())));
        
        public static GraphicColorSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightGoldenrodYellow")]
        public global::System.Drawing.Color DefaultEmptyFieldColor {
            get {
                return ((global::System.Drawing.Color)(this["DefaultEmptyFieldColor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ForestGreen")]
        public global::System.Drawing.Color DefaultSnakeFieldColor {
            get {
                return ((global::System.Drawing.Color)(this["DefaultSnakeFieldColor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkGreen")]
        public global::System.Drawing.Color DefaultFoodFieldColor {
            get {
                return ((global::System.Drawing.Color)(this["DefaultFoodFieldColor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkGray")]
        public global::System.Drawing.Color DefaultWallFieldColor {
            get {
                return ((global::System.Drawing.Color)(this["DefaultWallFieldColor"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightGoldenrodYellow")]
        public global::System.Drawing.Color CurrentEmptyFieldColor {
            get {
                return ((global::System.Drawing.Color)(this["CurrentEmptyFieldColor"]));
            }
            set {
                this["CurrentEmptyFieldColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ForestGreen")]
        public global::System.Drawing.Color CurrentSnakeFieldColor {
            get {
                return ((global::System.Drawing.Color)(this["CurrentSnakeFieldColor"]));
            }
            set {
                this["CurrentSnakeFieldColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkGreen")]
        public global::System.Drawing.Color CurrentFoodFieldColor {
            get {
                return ((global::System.Drawing.Color)(this["CurrentFoodFieldColor"]));
            }
            set {
                this["CurrentFoodFieldColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkGray")]
        public global::System.Drawing.Color CurrentWallFieldColor {
            get {
                return ((global::System.Drawing.Color)(this["CurrentWallFieldColor"]));
            }
            set {
                this["CurrentWallFieldColor"] = value;
            }
        }
    }
}
